debug = true

log_dir = .
log_name = ayame.jsonl
log_level = debug
log_stdout = true

# ローテーションするログの最大サイズ（MB）です
# log_rotate_max_size = 200
# 保持するログファイルの最大数です
# log_rotate_max_backups = 7
# 古いログファイルを保持する最大日数です
# log_rotate_max_age = 30
# ローテーションするログの圧縮を有効にするかどうかです
# log_rotate_compress = false

signaling_log_name = signaling.jsonl

# debug = true かつ debug_console_log = true の場合はデバッグコンソールログを出力します。
# debug_console_log = true
# debug_console_log_json = false

type_message = false

listen_ipv4_address = 0.0.0.0
listen_port_number = 3000

# websocket_read_timeout_sec = 90
# websocket_pong_timeout_sec = 60
# websocket_ping_interval_sec = 5

# authn_webhook_url = http://127.0.0.1:3001/ayame/webhook/authn
# disconnect_webhook_url = http://127.0.0.1:3001/ayame/webhook/disconnect
# webhook_request_timeout_sec = 5
# webhook_log_name = webhook.jsonl

listen_prometheus_ipv4_address = 0.0.0.0
listen_prometheus_port_number = 4000
