## ログの出力先ディレクトリを指定します
## デフォルトは . です
# log_dir = .

## ログのファイル名を指定します
## デフォルトは ayame.jsonl です
# log_name = ayame.jsonl

## 標準出力にログを出力するかを指定します
## デフォルトは false です
# log_stdout = true

## ローテーションするログの最大サイズ（MB）を指定します
## デフォルトは 200 です
# log_rotate_max_size = 200

## 保持するログファイルの最大数を指定します
## デフォルトは 7 です
# log_rotate_max_backups = 7

## 古いログファイルを保持する最大日数を指定します
## デフォルトは 30 です
# log_rotate_max_age = 30

## ローテーションするログの圧縮 (gzip)を有効にするかを指定します
## デフォルトは false です
# log_rotate_compress = true

## シグナリングログのファイル名を指定します
## デフォルトは signaling.jsonl です
# signaling_log_name = signaling.jsonl

## シグナリングログで出力する type を指定します
## デフォルトは全て出力します
## register,offer,answer,candidate,connected,message が指定できます
# signaling_log_filters = offer,answer

## デバッグモードを有効にするかを指定します
## デフォルトは false です
# debug = true

## デバッグコンソールログを出力するかを指定します
## デフォルトは false です
# debug_console_log = true

## デバッグコンソールログを JSON 形式で出力するかを指定します
## デフォルトは false です
# debug_console_log_json = true

## type: "message" を送受信できるようにするかを指定します
## デフォルトは false です
# type_message = true

## 待ち受ける IPv4 アドレスを指定します
## デフォルトは 0.0.0.0 です
# listen_ipv4_address = 0.0.0.0

## 待ち受けるポート番号を指定します
## デフォルトは 3000 です
# listen_port_number = 3000

## WebSocket の読み込みタイムアウト時間を指定します
## デフォルトは 90 秒です
# websocket_read_timeout_sec = 90

## WebSocket の Pong タイムアウト時間を指定します
## デフォルトは 60 秒です
# websocket_pong_timeout_sec = 60

## WebSocket の Ping 送信間隔を指定します
## デフォルトは 5 秒です
# websocket_ping_interval_sec = 5

## シグナリングで利用する WebSocket の HTTP ヘッダーをウェブフックにコピーするヘッダー名を指定します
## デフォルトは未指定です
# copy_websocket_header_names = X-Forwarded-For, X-Real-IP

## 認証 Webhook の URL を指定します
## デフォルトは未指定です
# authn_webhook_url = http://127.0.0.1:3001/ayame/webhook/authn

## 切断 Webhook の URL を指定します
## デフォルトは未指定です
# disconnect_webhook_url = http://127.0.0.1:3001/ayame/webhook/disconnect

## Webhook のリクエストタイムアウト時間を指定します
## デフォルトは 5 秒です
# webhook_request_timeout_sec = 5

## Webhook のログファイル名を指定します
## デフォルトは webhook.jsonl です
# webhook_log_name = webhook.jsonl

## 待ち受ける Prometheus の IPv4 アドレスを指定します
## デフォルトは 0.0.0.0 です
# listen_prometheus_ipv4_address = 0.0.0.0

## 待ち受ける Prometheus のポート番号を指定します
## デフォルトは 4000 です
# listen_prometheus_port_number = 4000
